version: '3'
services:
  adapter:
    image: "golang:${GOLANG_VERSION}"
    volumes:
      - .:/root/app
    working_dir: /root/app
    environment:
      - DB_HOST=adapter-mongodb
    links:
      - adapter-mongodb
    command: >
      sh -c "go version
      && go env
      && pwd
      && ls -la
      && go test -cover ./..."
  adapter-mongodb:
    image: "mongo:${MONGO_VERSION}"
    command: mongod --logpath=/dev/null # --quiet
